language: python
virtualenv:
  system_site_packages: true
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - py.test --cov=validate_transaction
# publish coverage only after a successful build
after_success:
  - codecov
notifications:
  email: false
branches:
  only:
    - master
    - develop